sudo: required
services:
    - docker

# before_install:
#   - docker build -t alcaamoti/react-app-dev -f Dockerfile.dev .

# script:
#   - docker run alcaamoti/react-app-dev npm run test -- --coverage

before_deploy:
  - docker build -t alcaamoti/react-app .

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
  on:
    branch: master


