sudo: required
services:
    - docker

before_install:
  - docker build -t alcaamoti/react-app -f Dockerfile.dev .

script:
  - docker run alcaamoti/react-app npm run test -- --coverage

after_success:
  - docker build -t alcaamoti/react-app .
  - bash scripts/deploy-client.sh

# deploy:
#   provider: script
#   script: bash scripts/deploy-client.sh
#   on:
#     branch: master


